version: '3.12.1'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  migration:
    build:
      context: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    command: python manage.py migrate --noinput
    depends_on:
      - postgres

  app:
    build: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - 8000:8000
    image: app:django
    container_name: my_django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - migration
      # - postgres
