version: '3.12.1'

services:
  migration:
    build:
      context: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    command: python manage.py migrate --noinput

  app:
    build: .
    volumes:
      - ${HOME}/bloomtest-2996c-firebase-adminsdk-qnpii-d0844416ae.json:/django/bloomtest-2996c-firebase-adminsdk-qnpii-d0844416ae.json
      - .:/django
    env_file:
      - path: .env
        required: true
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    ports:
      - 8000:8000
    image: app:django
    container_name: my_django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - migration
