# Generated by Django 4.1.2 on 2024-03-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_customuser_referral_code_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="facebook_auth_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="google_auth_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
