# Generated by Django 4.1.2 on 2024-03-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_customuser_facebook_auth_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="facebook_user_id",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("usage_number", models.PositiveIntegerField(default=0)),
                ("file_link", models.TextField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
