# Generated by Django 4.1.2 on 2024-03-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_customuser_facebook_user_id_otp_verified_story"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="file_link",
        ),
        migrations.AddField(
            model_name="story",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="story_uploads/"),
        ),
        migrations.AddField(
            model_name="story",
            name="used_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="story",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.story"
            ),
        ),
    ]
