# Generated by Django 4.1.2 on 2024-03-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_story_file_link_story_file_story_used_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="payable_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="bank_code",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="bank_name",
        ),
        migrations.AddField(
            model_name="transaction",
            name="file_downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="withdrawable_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_transactions",
                to="app.story",
            ),
        ),
    ]
