# Generated by Django 4.1.2 on 2024-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_customuser_account_number_customuser_acount_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="acount_name",
            new_name="account_name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="connected_account_id",
            new_name="bank_account_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank_name",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="customer_id",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="withdraw_account_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="withdraw_account_number",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="withdraw_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="withdraw_bank_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
