# Generated by Django 4.1.2 on 2024-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_acount_name_customuser_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referred_users",
            field=models.IntegerField(default=0),
        ),
    ]
