# Generated by Django 4.1.2 on 2024-04-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_customuser_firebase_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
