# Generated by Django 4.1.2 on 2024-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_customuser_stripe_setup_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.FileField(blank=True, null=True, upload_to="profile_pictures/"),
        ),
    ]
