name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  clear-and-prune:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clear app directory, stop containers, and prune system
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          set -e
          cd ~ || exit
          docker compose down || true
          docker system prune --force || true
          rm -rf app || true

  generate-env-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 instance, create app directory, and generate .env file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          set -e
          mkdir -p ~/app || true
          cd ~/app || exit
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
          echo "CORS_ORIGIN_ALLOW_ALL=${{ secrets.CORS_ORIGIN_ALLOW_ALL }}" >> .env
          echo "CORS_ALLOW_ALL_ORIGINS=${{ secrets.CORS_ALLOW_ALL_ORIGINS }}" >> .env
          echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> .env
          echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> .env
          echo "LIVE=${{ secrets.LIVE }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env 
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          echo "SHOW_DOCS=${{ secrets.SHOW_DOCS }}" >> .env
          echo "GOOGLE_OAUTH2_CLIENT_ID=${}" >> .env
          echo "GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}" >> .env
          echo "FACEBOOK_OAUTH_CLIENT_ID=${FACEBOOK_OAUTH_CLIENT_ID}" >> .env
          echo "FACEBOOK_OAUTH_CLIENT_SECRET=${FACEBOOK_OAUTH_CLIENT_SECRET}" >> .env
          echo "AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}" >> .env
          echo "AWS_QUERYSTRING_AUTH=${{ secrets.AWS_QUERYSTRING_AUTH }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env
          echo "STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}" >> .env
          echo "FRONT_END_SHARE_STORY_URL=${FRONT_END_SHARE_STORY_URL}" >> .env
          echo "FRONTEND_GOOGLE_OAUTH_URL=${FRONTEND_GOOGLE_OAUTH_URL}" >> .env
          echo "FRONTEND_FACEBOOK_OAUTH_URL=${FRONTEND_FACEBOOK_OAUTH_URL}" >> .env
          echo "FRONTEND_DOWNLOAD_ERROR_URL=${FRONTEND_DOWNLOAD_ERROR_URL}" >> .env
          echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" >> .env
          echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> .env
          echo "BACKEND_DOWNLOAD_URL=${}/api/v1/download/?token" >> .env
          echo "GENERATE_CODE=${{ secrets.GENERATE_CODE }}" >> .env || true

    - name: Copy files to EC2 instance and deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: .
        target: ~/app || true

    - name: SSH into EC2 instance, build Docker images, and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          set -e
          cd ~/app || exit
          docker compose build || true
          docker compose up -d || true
